/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.seatecnologia.cldf.enquetenoticia.model.impl;

import br.com.seatecnologia.cldf.enquetenoticia.model.EnqueteNoticia;
import br.com.seatecnologia.cldf.enquetenoticia.service.EnqueteNoticiaLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EnqueteNoticia service. Represents a row in the &quot;EnqueteNoticia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EnqueteNoticiaImpl}.
 * </p>
 *
 * @author Wallacy, Adan, Eduardo
 * @see EnqueteNoticiaImpl
 * @see br.com.seatecnologia.cldf.enquetenoticia.model.EnqueteNoticia
 * @generated
 */
public abstract class EnqueteNoticiaBaseImpl extends EnqueteNoticiaModelImpl
	implements EnqueteNoticia {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a enquete noticia model instance should use the {@link EnqueteNoticia} interface instead.
	 */
	public void persist() throws SystemException {
		EnqueteNoticiaLocalServiceUtil.updateEnqueteNoticia(this);
	}
}