/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.seatecnologia.cldf.enquetenoticia.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EnqueteNoticia service. Represents a row in the &quot;EnqueteNoticia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.seatecnologia.cldf.enquetenoticia.model.impl.EnqueteNoticiaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.seatecnologia.cldf.enquetenoticia.model.impl.EnqueteNoticiaImpl}.
 * </p>
 *
 * @author Wallacy
 * @see EnqueteNoticia
 * @see br.com.seatecnologia.cldf.enquetenoticia.model.impl.EnqueteNoticiaImpl
 * @see br.com.seatecnologia.cldf.enquetenoticia.model.impl.EnqueteNoticiaModelImpl
 * @generated
 */
public interface EnqueteNoticiaModel extends BaseModel<EnqueteNoticia> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a enquete noticia model instance should use the {@link EnqueteNoticia} interface instead.
	 */

	/**
	 * Gets the primary key of this enquete noticia.
	 *
	 * @return the primary key of this enquete noticia
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this enquete noticia
	 *
	 * @param primaryKey the primary key of this enquete noticia
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Gets the enquete noticia ID of this enquete noticia.
	 *
	 * @return the enquete noticia ID of this enquete noticia
	 */
	public long getEnqueteNoticiaId();

	/**
	 * Sets the enquete noticia ID of this enquete noticia.
	 *
	 * @param enqueteNoticiaId the enquete noticia ID of this enquete noticia
	 */
	public void setEnqueteNoticiaId(long enqueteNoticiaId);

	/**
	 * Gets the question ID of this enquete noticia.
	 *
	 * @return the question ID of this enquete noticia
	 */
	public long getQuestionId();

	/**
	 * Sets the question ID of this enquete noticia.
	 *
	 * @param questionId the question ID of this enquete noticia
	 */
	public void setQuestionId(long questionId);

	/**
	 * Gets the article ID of this enquete noticia.
	 *
	 * @return the article ID of this enquete noticia
	 */
	public long getArticleId();

	/**
	 * Sets the article ID of this enquete noticia.
	 *
	 * @param articleId the article ID of this enquete noticia
	 */
	public void setArticleId(long articleId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(EnqueteNoticia enqueteNoticia);

	public int hashCode();

	public CacheModel<EnqueteNoticia> toCacheModel();

	public EnqueteNoticia toEscapedModel();

	public String toString();

	public String toXmlString();
}